version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: groovielive-nginx
    restart: always
    volumes:
      - ./ReverseProxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8081:8081'
    depends_on:
      - node
      - spring
      - react
      - flask

  react:
    container_name: groovielive-react
    build: 
      context: ./ReactJS/my-app
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - node

  node:
    container_name: groovielive-node
    build: 
      context: ./GroovieLiveNode
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - spring
      - flask

  spring:
    container_name: groovielive-spring
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    
  flask:
    container_name: groovielive-flask
    build: 
      context: ./IA/recommendationService/recommendationService
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
