DROP TABLE IF EXISTS dbUser;

CREATE SEQUENCE USERDB_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE UserDB (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    username VARCHAR(250) NOT NULL,
    password VARCHAR(250) NOT NULL,
    email VARCHAR(250) NOT NULL,
    role VARCHAR(250) NOT NULL
);